TMGR-56:clossing modal by "esc"
tmgr-dev/frontend pull request #61
Opened 2023-03-03 18:38 UTC by mykolasenyuk

2023-03-03 18:43 UTC, acrossoffwest commented
This pull request has been automatically deployed.
✅ Preview: https://tmgr-feature-tmgr-56.surge.sh
🔍 Logs: https://github.com/tmgr-dev/frontend/actions/runs/4326320573

2023-03-03 23:06 UTC, acrossoffwest commented
1. Если задача не сохранена сохранить её - не работает
2. Вы уверены надо спросить при нажатии отмена тоже в случае если юзер добавил данных о новой задаче - не работает
3. При создании задачи когда кликаю эскейп тайтл не заполнен и дескрипшн тоже, показывает мне модалку с подтверждением - это не правильно

2023-03-04 09:30 UTC, savayer requested changes

2023-03-04 09:30 UTC, savayer commented on src/utils/stringUtils.js
> +};
выглядит оч странно, вообще не нужна такая утилита.
1. ни разу не видел чтобы сравнивали переменную с объектом String, обычно пишут typeof varName === 'string'. Ну и любавя строка этому объекту естественно равна не будет
2. все три условия возвращают тру

Условия `this.form.title && this.form.description` вполне достаточно, чтобы получить желаемую проверку

2023-03-04 13:26 UTC, acrossoffwest commented on src/utils/stringUtils.js
> +};
@savayer утилиту я просил сделать, с этим ок. а вот нулл и андефайнед вопрос вообще целесообразно ли или нет но я попросил сравнивать это)

2023-03-04 14:07 UTC, savayer commented on src/utils/stringUtils.js
> +};
ну хз, утилита которая проверяет, что строка тру выглядит как оверкилл

2023-03-04 14:09 UTC, acrossoffwest commented on src/utils/stringUtils.js
> +};
ну ещё чего нибудь добавим далее

2023-03-04 14:10 UTC, savayer commented on src/utils/stringUtils.js
> +};
ну когда что-то будет необходимое, тогда и создадим

2023-03-04 14:12 UTC, acrossoffwest commented on src/utils/stringUtils.js
> +};
Хорошо, тогда @mykolasenyuk убирай и выноси это условие из файла этого и удаляй его

2023-03-04 14:12 UTC, savayer commented on src/utils/stringUtils.js
> +};
ты если руководствуешься паттерном каким-нибудь, просвяти тогда уж )

2023-03-04 14:19 UTC, acrossoffwest commented on src/utils/stringUtils.js
> +};
> 

да нет никакого паттерна просто оверинжиниринг)

2023-03-06 15:12 UTC, merged