TMGR-42: change to Composition API
tmgr-dev/frontend pull request #67
Opened 2023-03-14 16:28 UTC by mykolasenyuk

2023-03-14 16:31 UTC, acrossoffwest commented
This pull request has been automatically deployed.
✅ Preview: https://tmgr-tmgr-42-ts.surge.sh
🔍 Logs: https://github.com/tmgr-dev/frontend/actions/runs/4417988950

2023-03-15 01:33 UTC, savayer requested changes

2023-03-15 01:33 UTC, savayer commented on src/components/general/AssigneeAvatar.vue
> +	interface assigneeType {
интерфейс с большой буквы

2023-03-15 01:33 UTC, savayer commented on src/components/general/AssigneeAvatar.vue
> +		setup({ assignee, showRemovingAssignee = true }: Props): Data {
setup можешь в <script > добавить

2023-03-15 01:33 UTC, savayer commented on src/components/general/AssigneeUsers.vue
> +	const props = defineProps<Props>();
дефолтные значение не указаны как ниже с options api

2023-03-15 01:33 UTC, savayer commented on src/pages/TaskForm.vue
> +						:isModal="isModal"
тогда может isPage вообще можно удалить?

2023-03-15 01:33 UTC, savayer commented on src/components/general/AssigneeUsers.vue
> +	// };
это зачем оставлено?

2023-03-15 01:34 UTC, savayer commented on src/components/general/AssigneeAvatar.vue
> +	interface assigneeType {
но если в названии type, то тогда это и не интерфейс )

2023-03-25 03:25 UTC, merged