Feature/tm 24
tmgr-dev/frontend pull request #78
Opened 2023-04-19 11:50 UTC by mykolasenyuk

2023-04-19 11:54 UTC, acrossoffwest commented
This pull request has been automatically deployed.
✅ Preview: https://tmgr-feature-tm-24.surge.sh
🔍 Logs: https://github.com/tmgr-dev/frontend/actions/runs/4742939758

2023-04-25 10:16 UTC, savayer requested changes

2023-04-25 10:16 UTC, savayer commented on src/pages/ProjectCategoryList.vue
> +											>
выглядит страшно же ) Добавь отступ и сохрани prettier подхватит. Можешь поиграться с его параметрами чтобы не допускать такого форматирования

2023-04-26 03:43 UTC, savayer commented
почему коммиты зовутся TMGR а ветка TM? Fixes after review не дает представления о том что содержит коммит, лучше в этом случае fixed formatting

2023-04-26 03:44 UTC, merged