TMGR-11: reordering statuses
tmgr-dev/frontend pull request #79
Opened 2023-04-25 08:58 UTC by mykolasenyuk

2023-04-25 09:02 UTC, acrossoffwest commented
This pull request has been automatically deployed.
✅ Preview: https://tmgr-feature-tm-11.surge.sh
🔍 Logs: https://github.com/tmgr-dev/frontend/actions/runs/4795607344

2023-04-25 10:13 UTC, savayer requested changes
<img width="1601" alt="image" src="https://user-images.githubusercontent.com/19423784/234246507-aaa36326-626e-4c11-aac6-f359c27c5d59.png">

пропал отступ

2023-04-25 10:13 UTC, savayer commented on src/actions/tmgr/workspaces.ts
> +
мне кажется фронту без разницы пивот там или не пивот, в урле работаешь с order, может лучше order и назвать? updateWorkspaceOrder

2023-04-25 10:19 UTC, savayer commented
фильтры появляются и смещают всё что ниже

2023-04-25 10:20 UTC, mykolasenyuk commented on src/components/general/FiltersBoard.vue
> +				/>
https://www.figma.com/file/k6F0dKE9VKpZNhpULPcv77/TMGR-new-features-schemes?node-id=1-178&t=ZT1YNlYcRMFNzeXw-0

2023-04-25 10:22 UTC, savayer commented on src/components/general/FiltersBoard.vue
> +				/>
ну хз так себе выглядит

2023-04-25 10:52 UTC, mykolasenyuk commented
А как должно бить?

On Tue, 25 Apr 2023, 13:19 savayer, ***@***.***> wrote:

> фильтры появляются и смещают всё что ниже
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/tmgr-dev/frontend/pull/79#issuecomment-1521539532>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARNHIT5MFMNIOJOYC3RMBY3XC6QK5ANCNFSM6AAAAAAXKWACYM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-04-25 10:57 UTC, savayer commented
https://web.dev/cls/

2023-04-26 03:49 UTC, savayer requested changes

2023-04-26 03:49 UTC, savayer commented on tailwind.config.js
> +			},
не пиши такое в конфиги

2023-04-26 03:49 UTC, savayer commented on tailwind.config.js
> +			},
Что если такая высота будет но НЕ у фильтров?

2023-04-26 06:51 UTC, mykolasenyuk commented on tailwind.config.js
> +			},
а как лучше 15? типа "min-h-15"?

2023-04-26 10:23 UTC, acrossoffwest commented on src/components/general/FiltersBoard.vue
> +				/>
> 

надо бы свитч какой сделать, но это уже в рамках другой задачи

2023-04-26 10:23 UTC, acrossoffwest commented on src/components/general/FiltersBoard.vue
> +				/>
да и в целом редизайн будет позже

2023-04-26 14:34 UTC, merged

2023-04-28 10:00 UTC, savayer commented on tailwind.config.js
> +			},
у min-h вообще не предусмотрены размеры по дефолту в TW. Так что можно и min-h-[62px] написать, плюс 15 это 60px. В конфиги лучше писать реально то что юзается. А где еще минимальная высота 60 будет юзаться хз

2023-04-28 10:00 UTC, savayer commented on tailwind.config.js
> +			},
@mykolasenyuk