Feature/tm 10
tmgr-dev/frontend pull request #84
Opened 2023-05-02 11:34 UTC by mykolasenyuk

2023-05-02 12:08 UTC, savayer requested changes

2023-05-02 12:08 UTC, savayer commented on src/pages/Board.vue
> +			},
это определенно не относится к этому компоненту, надо вынести в utils

2023-05-02 12:08 UTC, savayer commented on src/pages/Board.vue
> +			},
и это тоже

2023-05-02 12:08 UTC, savayer commented on src/pages/Board.vue
> +				}
а если пробелы будут?

2023-05-02 12:08 UTC, savayer commented on src/pages/Board.vue
> +			},
дублирование кода

2023-05-02 12:08 UTC, savayer commented on src/pages/Board.vue
>  			getActions(column) {
это я удалил, в деве этого нет. Ты откуда ветку создавал? Там еще конфликты

2023-05-02 12:09 UTC, savayer commented on src/pages/Board.vue
>  			getActions(column) {
мержи дев в текущую ветку и резолвь конфликты

2023-05-02 12:10 UTC, savayer commented on src/pages/Board.vue
>  			getActions(column) {
чтобы конфликты пофиксить смержи дев в текущую ветку

2023-05-03 07:29 UTC, acrossoffwest commented
This pull request has been automatically deployed.
✅ Preview: https://tmgr-feature-tm-10.surge.sh
🔍 Logs: https://github.com/tmgr-dev/frontend/actions/runs/4869364087

2023-05-03 07:41 UTC, savayer requested changes
<img width="417" alt="image" src="https://user-images.githubusercontent.com/19423784/235857246-cdb33bd5-1be7-4ccc-8dae-5cd56f3d3e5e.png">

отступов не хватает. шрифт тонкий слишком можно медиум поставить

status color слишком большой, можно его пониже и в одну линии с текстом сделать как девтулзах хрома в стилях

2023-05-03 07:41 UTC, savayer commented on src/pages/Board.vue
> +									</label>
тут дублирование опять

2023-05-03 07:41 UTC, savayer commented on src/actions/tmgr/statuses.ts
> +	return;
это можно удалить

2023-05-03 07:41 UTC, savayer commented on package.json
> +		"@radial-color-picker/vue-color-picker": "^5.0.1",
<img width="1263" alt="image" src="https://user-images.githubusercontent.com/19423784/235856546-7ee2f140-8ac3-4691-af97-64df8fa8183e.png">

точно чего-нибудь более популярного и свежего нет?

2023-05-03 07:41 UTC, savayer commented on package.json
> +		"@radial-color-picker/vue-color-picker": "^5.0.1",
почему решили радиальный сделать?

2023-05-03 10:14 UTC, savayer commented on package.json
> +		"@radial-color-picker/vue-color-picker": "^5.0.1",
ну да но явно можно получше найти и не обязательно на вью

2023-05-03 10:15 UTC, savayer commented on package.json
> +		"@radial-color-picker/vue-color-picker": "^5.0.1",
имею в виду можно ванилла

2023-05-03 10:16 UTC, savayer commented on package.json
> +		"@radial-color-picker/vue-color-picker": "^5.0.1",
<img width="300" alt="image" src="https://user-images.githubusercontent.com/19423784/235889921-af76179e-5008-4b73-ac8e-0fb14f7fa347.png">
вот так было б ништячок

2023-05-03 10:17 UTC, mykolasenyuk commented on package.json
> +		"@radial-color-picker/vue-color-picker": "^5.0.1",
да ну)

2023-05-03 10:18 UTC, savayer commented on package.json
> +		"@radial-color-picker/vue-color-picker": "^5.0.1",
явно больше выбора цветов становится

2023-05-03 10:18 UTC, savayer commented on package.json
> +		"@radial-color-picker/vue-color-picker": "^5.0.1",
и вполне стандартный вид

2023-05-03 10:19 UTC, mykolasenyuk commented on package.json
> +		"@radial-color-picker/vue-color-picker": "^5.0.1",
ет где то с 2000х, Windows millenium)

2023-05-03 10:20 UTC, mykolasenyuk commented on package.json
> +		"@radial-color-picker/vue-color-picker": "^5.0.1",
а сколько статусов там будут создавать 1000?зачем так много?

2023-05-03 10:21 UTC, savayer commented on package.json
> +		"@radial-color-picker/vue-color-picker": "^5.0.1",
не согласен, твой скрин возможно да. В девтулзах в хроме такой же вид. Другого ты не найдешь, радиальный даёт небольшой выбор, мб конкретно тот что ты поставил

2023-05-03 10:24 UTC, mykolasenyuk commented on package.json
> +		"@radial-color-picker/vue-color-picker": "^5.0.1",
так что должно бить как в девтулзах?

2023-05-03 10:25 UTC, savayer commented on package.json
> +		"@radial-color-picker/vue-color-picker": "^5.0.1",
> а сколько статусов там будут создавать 1000?зачем так много?

ну в теории если это запустится, то почему нет?)

2023-05-03 10:27 UTC, mykolasenyuk commented on package.json
> +		"@radial-color-picker/vue-color-picker": "^5.0.1",
ниразу не видел чтоб било столько

2023-05-03 10:27 UTC, savayer commented on package.json
> +		"@radial-color-picker/vue-color-picker": "^5.0.1",
> так что должно бить как в девтулзах?

не понимаю твоего вопроса

<img width="494" alt="image" src="https://user-images.githubusercontent.com/19423784/235891872-6dcc16b4-cf55-4331-8947-8fdc5a726781.png">

2023-05-03 10:28 UTC, savayer commented on package.json
> +		"@radial-color-picker/vue-color-picker": "^5.0.1",
> ниразу не видел чтоб било столько

слушай не хочешь делать я сам переделаю

2023-05-03 10:34 UTC, mykolasenyuk commented on package.json
> +		"@radial-color-picker/vue-color-picker": "^5.0.1",
ну как знаешь, мне тот больше нравится

2023-05-03 10:37 UTC, mykolasenyuk commented on package.json
> +		"@radial-color-picker/vue-color-picker": "^5.0.1",
не думаю что будет 1000 статусов,лутче воркспейс новий создать)

2023-05-03 10:40 UTC, savayer commented
<img width="645" alt="image" src="https://user-images.githubusercontent.com/19423784/235894190-121dcf1e-e220-45c6-86cf-0fa21bed27aa.png">

удаляю статус не удаляется и написано таск

2023-05-03 10:41 UTC, savayer commented
<img width="300" alt="image" src="https://user-images.githubusercontent.com/19423784/235894309-5c5aa829-c4eb-48b6-a7cd-d9919627156f.png">

тут либо всё с маленькой буквы напиши либо все с большой

2023-05-03 10:42 UTC, savayer commented
<img width="748" alt="image" src="https://user-images.githubusercontent.com/19423784/235894723-5bffab09-1e44-46ab-ac11-59b077b30bdc.png">

это че?)

2023-05-03 10:45 UTC, savayer commented
<img width="686" alt="image" src="https://user-images.githubusercontent.com/19423784/235895244-957ea567-a614-4eb1-8682-d6728640e225.png">

дожно быть так

2023-05-03 10:46 UTC, savayer commented on package.json
> +		"@radial-color-picker/vue-color-picker": "^5.0.1",
ну 1000 не 1000, но там явно мало, на 20 не хватит

2023-05-03 10:46 UTC, savayer commented on package.json
> +		"@radial-color-picker/vue-color-picker": "^5.0.1",
но как выглядит неплохо соглы

2023-05-05 10:22 UTC, merged